---
# Configuration file for MegaLinter.
# See configuration options at https://oxsecurity.github.io/megalinter/configuration/ and more in each linter documentation.

# General
PRINT_ALPACA: false
APPLY_FIXES: all

DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true

# Reporter options
CLEAR_REPORT_FOLDER: true
EMAIL_REPORTER: false
TEXT_REPORTER: true
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: true
GITLAB_COMMENT_REPORTER: false
UPDATED_SOURCES_REPORTER: true

# Linters

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default

ENABLE_LINTERS:
  [
    BASH_SHELLCHECK,
    COPYPASTE,
    CSS_STYLELINT,
    DOCKERFILE_HADOLINT,
    REPOSITORY_GITLEAKS,
    REPOSITORY_SECRETLINT,
    JAVA_CHECKSTYLE,
    JAVA_PMD,
    JSON_PRETTIER,
    MARKDOWN_MARKDOWN_LINT,
    YAML_PRETTIER,
    XML_XMLLINT,
  ]

# Specific linter options

JAVA_CHECKSTYLE_FILTER_REGEX_INCLUDE: src/main
JAVA_CHECKSTYLE_CONFIG_FILE: configs/checkstyle_sun_checks_mod.xml
JAVA_PMD_CONFIG_FILE: configs/pmd_default_java_mod.xml
COPYPASTE_JSCPD_ARGUMENTS: --ignore "**/build/**","report","LICENSES",".idea/**" --threshold "10"
