name: Maven build

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  maven-matrix-build:
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17]
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: "temurin"
      
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Executable Maven wrapper
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Maven Package
        run: ./mvnw --batch-mode --update-snapshots --file pom.xml package
