---
name: Conform DCO (--Sign-off)
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  signoff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create conform.yml
        run: |
          cat <<EOF > .conform.yaml
          policies:
            - type: commit
              spec:
                dco: true
          EOF
          cat .conform.yaml
      - name: Conform Action
        uses: siderolabs/conform@v0.1.0-alpha.26
