name: GUITag
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag format: v(semver) please"
        required: true
      
      message:
        description: "Tag message"
        required: false

jobs:
  tag:
    name: GUI-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: madhead/semver-utils@latest
        id: semvercheck
        with:
          version: ${{ github.event.inputs.version }}
          lenient: false
        continue-on-error: false
      - run: |
          echo "${{ steps.semvercheck.outcome }}"
      
      - name: Tag from GUI!
        uses: anothrNick/github-tag-action@1.40.0
        if: ${{ success() }}
        run: |
          tag=${{ github.event.inputs.version }}
          message=${{ github.event.inputs.version }}

          git config user.name 'github-actions-manual-trigger[bot]'
          git config user.email 'github-actions-manual-trigger[bot]@users.noreply.github.com'

          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
