name: GUITag
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag format: v(semver) please"
        required: true
      
      message:
        description: "Tag message"
        required: false

jobs:
  tag:
    name: GUI-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # This is important if you have branch protection rules!

      - name: Semver check input
      - uses: madhead/semver-utils@latest
        id: semvercheck
        with:
          version: ${{ github.event.inputs.version }}
          lenient: false
        continue-on-error: false
      - run: |
          echo "${{ steps.semvercheck.outcome }}"
      
      - name: Import bot's GPG key for signing
        id: import-gpg
        if: ${{ success() }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_tag_gpgsign: true
      
      - name: Tag from GUI!
        if: ${{ success() }}
        run: |
          tag=${{ github.event.inputs.version }}
          message=${{ github.event.inputs.version }}

          git tag -s -a "${tag}" -m "${message}"
          git push origin "${tag}"
