name: GUITag
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag format: v(semver) please"
        required: true

jobs:
  tag:
    name: GUI-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: madhead/semver-utils@latest
        id: semvercheck
        with:
          version: ${{ github.event.inputs.version }}
          lenient: false
        continue-on-error: false
      - run: |
          echo "${{ steps.semvercheck.outcome }}"
      
      - name: Tag from GUI!
        uses: anothrNick/github-tag-action@1.40.0
        if: ${{ github.event.inputs.version  != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ github.event.inputs.version }}
