name: Manual Tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (semver please)"
        required: true

jobs:
  tag:
    name: Manual tag
    runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Tag from GUI!
      uses: anothrNick/github-tag-action@1.40.0
      if: ${{ github.event.inputs.version  != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ github.event.inputs.version  != '' }}
