---
name: sariftool workflow

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  # workflow_run: tagging from workflow event does not trigger
  #  workflows: ["GUITag"]
  #  types:
  #    - completed
  pull_request:
    branches:
      - main

jobs:
  dco:
    uses: ./.github/workflows/dco.yml
  commitlint:
    uses: ./.github/workflows/commitlint.yml
  license:
    uses: ./.github/workflows/license.yml
  lint:
    uses: ./.github/workflows/lint.yml
  repolint:
    uses: ./.github/workflows/repolint.yml
  test:
    needs: [dco, commitlint, license, lint, repolint]
    uses: ./.github/workflows/build.yml
  native-build:
    needs: [test]
    uses: ./.github/workflows/native-image.yml
  publish-container-image:
    needs: [native-build]
    uses: ./.github/workflows/publish-container.yml
